### ISSUE TITLE
[fix] Namesets panel blocks with "World configuration unavailable" / invalid world ID

### ISSUE THREAD

**Issue by DylanLogan2581** [DylanLogan2581/gubernator#628]
## Current Behavior

On the world configuration page, the **Namesets** panel renders a blocking error:

> World configuration unavailable
>
> The world ID is invalid. Please reload the page or contact support if the issue persists.

Root cause: commit `2c417aa` (fix #620) added a client-side UUID guard that is unique to this panel and now blocks it. At [NamesetsConfigPanel.tsx:125](src/features/namesets/components/NamesetsConfigPanel.tsx#L125):

```ts
const isWorldIdValid = z.string().uuid().safeParse(worldId).success;
```

When this fails, the panel disables "Add nameset" ([:150](src/features/namesets/components/NamesetsConfigPanel.tsx#L150)) and renders the `ErrorState` ([:179-183](src/features/namesets/components/NamesetsConfigPanel.tsx#L179-L183)) instead of the namesets UI.

Why this is suspect as a false positive:
- Every sibling config panel (Resources, Jobs, Buildings, Deposits, Managed Populations) receives the **identical** `worldId` prop from the same route param ([WorldConfigurationPage.tsx:181](src/features/worlds/components/WorldConfigurationPage.tsx#L181) etc.) and none of them validate it — they render fine.
- The route `beforeLoad` already runs `worldRouteAccessQueryOptions(params.worldId)` ([worlds.$worldId.configuration.tsx:75](src/routes/worlds.$worldId.configuration.tsx#L75)); a genuinely invalid world would redirect before this panel ever renders.
- The `namesetsByWorldQuery` at [:77](src/features/namesets/components/NamesetsConfigPanel.tsx#L77) succeeds (no "Namesets could not be loaded" error), yet the UUID check downstream still fails — inconsistent with `worldId` being invalid.
- The project is on **zod 4.3.6**, where `z.string().uuid()` is deprecated and version-strict; it may reject a value the rest of the app accepts.

The actual offending value is logged at [:128](src/features/namesets/components/NamesetsConfigPanel.tsx#L128) via `console.warn` — capture it during repro to confirm whether `worldId` is genuinely `undefined`/empty or a valid UUID wrongly rejected.

## Expected Behavior

The Namesets panel renders normally on a valid world configuration page, consistent with the sibling config panels. The worldId guard does not produce false positives that block the panel.

## Reproduction Steps

1. Open a world configuration page.
2. Scroll to the Namesets panel.
3. Observe the "World configuration unavailable / The world ID is invalid" error.
4. Check the browser console for `Invalid worldId received in NamesetsConfigPanel:` and record the logged value.

## Acceptance Criteria

- [ ] Console-logged `worldId` value captured and the real cause confirmed (undefined/empty vs. valid-UUID-rejected-by-zod).
- [ ] If `worldId` is valid: the guard is corrected or removed so the panel renders; if zod v4 `z.string().uuid()` is the culprit, switch to top-level `z.uuid()` or align with how sibling panels treat worldId.
- [ ] If `worldId` is genuinely undefined: the source is fixed (route/prop typing), not just the symptom — sibling panels are handled consistently.
- [ ] Namesets panel renders and "Add nameset" works on a valid world; #620 mutation guard against truly-invalid input is preserved.
- [ ] No `console.warn` left firing on valid worlds.

## Notes

Regression from #620 / `2c417aa`. Related: #620.
